### ISSUE TITLE
Each person create own bigraph

### ISSUE THREAD

**Issue by nicccc5** [amirmghaemi/smarter-university-system#22]
Activity for epic #21 
Apply the binary tree method discussed in class. All members of your team should apply the technique independently and you should combine the priorities of team members into an overall priority for each requirement. More specifically, every team member should take the list of requirements.
Using the binary tree algorithm, consider each of the requirements. Starting with the first requirement as the root node, take any subsequent requirement and decide if it is more or less important than the requirements already in the tree. Follow the procedure discussed in class to create a binary tree (one for each team member).
![image](https://github.com/amirmghaemi/smarter-university-system/assets/48426765/f5f4ea4b-5f89-486c-9da4-dff6d36457ad)

**Comment by amirmghaemi** [comment]
digraph amir_ghaemi{
    1 -> 2
    2 -> 27
    27 -> 6
    6 -> 7
    7 -> 9
    9 -> 19
    19 -> 20
    20 -> 4
    4 -> 3
    3 -> 10
    10 -> 12
    12 -> 11
    11 -> 5
    5 -> 21
    21 -> 22
    22 -> 23
    23 -> 14
    14 -> 32
    32 -> 28
    28 -> 24
    24 -> 33
    33 -> 29
    29 -> 31
    31 -> 26
    26 -> 8
    8 -> 25
    25 -> 30
    30 -> 13
    13 -> 17
    17 -> 18
    18 -> 15
    15 -> 16

    // Placeholder nodes
    1 -> "1R"
    2 -> "2R"
    27 -> "27R"
    6 -> "6R"
    7 -> "7R"
    9 -> "9R"
    19 -> "19R"
    20 -> "20R"
    4 -> "4R"
    3 -> "3R"
    10 -> "10R"
    12 -> "12R"
    11 -> "11R"
    5 -> "5R"
    21 -> "21R"
    22 -> "22R"
    23 -> "23R"
    14 -> "14R"
    32 -> "32R"
    28 -> "28R"
    24 -> "24R"
    33 -> "33R"
    29 -> "29R"
    31 -> "31R"
    26 -> "26R"
    8 -> "8R"
    25 -> "25R"
    30 -> "30R"
    13 -> "13R"
    17 -> "17R"
    18 -> "18R"
    15 -> "15R"
}

**Comment by amirmghaemi** [comment]
The overall priority that I calculated is on the spreadsheet: https://docs.google.com/spreadsheets/d/1qb6YYKoZHaDZROnTtij4UkLvMcWVShHk/edit#gid=158603116

![graphviz (1)](https://github.com/amirmghaemi/smarter-university-system/assets/51731855/521674c6-ebd8-4cb5-9ca5-acb621cc7605)


The code for it, is as:
```dot
digraph over_all{
    1 -> 3
    3 -> 2
    2 -> 4
    4 -> 6
    6 -> 5
    5 -> 7
    7 -> 8
    8 -> 20
    20 -> 23
    23 -> 12
    12 -> 9
    9 -> 14
    14 -> 11
    11 -> 32
    32 -> 10
    10 -> 27
    27 -> 29
    29 -> 16
    16 -> 17
    17 -> 24
    24 -> 22
    22 -> 25
    25 -> 13
    13 -> 19
    19 -> 21
    21 -> 30
    30 -> 31
    31 -> 26
    26 -> 15
    15 -> 28
    28 -> 18
    18 -> 33

    // Placeholder nodes
    1 -> "1R"
    2 -> "2R"
    16 -> "16R"
    27 -> "27R"
    6 -> "6R"
    7 -> "7R"
    9 -> "9R"
    19 -> "19R"
    20 -> "20R"
    4 -> "4R"
    3 -> "3R"
    10 -> "10R"
    12 -> "12R"
    11 -> "11R"
    5 -> "5R"
    21 -> "21R"
    22 -> "22R"
    23 -> "23R"
    14 -> "14R"
    32 -> "32R"
    28 -> "28R"
    24 -> "24R"
    29 -> "29R"
    31 -> "31R"
    26 -> "26R"
    8 -> "8R"
    25 -> "25R"
    30 -> "30R"
    13 -> "13R"
    17 -> "17R"
    18 -> "18R"
    15 -> "15R"
}
```
