### ISSUE TITLE
Create Bigraph- Jin

### ISSUE THREAD

**Issue by nicccc5** [amirmghaemi/smarter-university-system#26]
Sub-activity for Activity #22

**Comment by liu01725** [comment]
Bigraph:


![Image](https://github.com/amirmghaemi/smarter-university-system/assets/90286026/35c684be-2f09-445e-b8c6-5bd12f0d7e92)

Code: 
digraph jin_liu {
    27 -> 25
    27 -> 19
    25 -> 31
    25 -> 8
    8 -> 20
    8 -> 5
    19 -> 12
    19 -> 2
    2 -> 16
    2 -> 6
    20 -> 15
    20 -> 26
    12 -> 13
    12 -> 18        
    5 -> 30
    5 -> 3
    16 -> L16
    16 -> 11
    6 -> 1
    6 -> 9
    18 -> 22
    18 -> 17
    13 -> 14
    13 -> 10
    31 -> 28
    31 -> 29
    28 -> 4
    28 -> 23
    29 -> 24
    29 -> 21
    30 -> 32
    30 -> R30
    4 -> 33
    4 -> R4
    23 -> L23
    23 -> 7
    
}
