### ISSUE TITLE
Create API test cases - Nicole

### ISSUE THREAD

**Issue by nicccc5** [amirmghaemi/smarter-university-system#27]
activity for epic #6

**Comment by amirmghaemi** [comment]
https://docs.google.com/spreadsheets/d/1guYwBOeM6ihSojcEIj_R-6xP9E1Jx0UIA0jvajiUcGY/edit?usp=sharing

**Comment by nicccc5** [comment]
Test Cases
1.  Invalid use of the API endpoint with a directed parameter set to TRUE and no recipients specified.
2. Invalid use of the API endpoint with a recipients parameter specified when directed is FALSE.
3. Invalid use of the API endpoint with a lat value but no lon value.
4. Invalid use of the API endpoint with a lon value but no lat value.
