### ISSUE TITLE
Create API test cases- Rishab

### ISSUE THREAD

**Issue by nicccc5** [amirmghaemi/smarter-university-system#30]
activity for epic #6

**Comment by amirmghaemi** [comment]
https://docs.google.com/spreadsheets/d/1guYwBOeM6ihSojcEIj_R-6xP9E1Jx0UIA0jvajiUcGY/edit?usp=sharing

**Comment by amirmghaemi** [comment]
I put in another few. @nicccc5 can you fill the list through row 60 please? Thanks!

**Comment by nicccc5** [comment]
Got it. Once I fill it to 60, I'll close the tickets.

**Comment by nicccc5** [comment]
I've updated the test case till 60.
